In [25]:
import numpy as np
from scipy import stats

In [26]:
#даны значения - три группы спортсменов - футболисты, хоккеисты, штангисты (качественные показатели)
#рост спортсменов в каждой группе - количественные показатели
#сформулируем нулевую гипотезу: различия среднего роста среди взрослых футболистов, хоккеистов и штангистов нет
y_1 = np.array([173, 175, 180, 178, 177, 185, 183, 182])
y_1

array([173, 175, 180, 178, 177, 185, 183, 182])

In [27]:
y_2 = np.array([177, 179, 180, 188, 177, 172, 171, 184, 180])
y_2

array([177, 179, 180, 188, 177, 172, 171, 184, 180])

In [28]:
y_3 = np.array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])
y_3

array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])

In [17]:
stats.f_oneway(y_1, y_2, y_3)

F_onewayResult(statistic=5.500053450812596, pvalue=0.010482206918698694)

In [ ]:
#если альфа = 5% или 0.05, то подтверждается альтернативная гипотеза, что различия среднего роста есть, 
#т.к. pvalue меньше альфа
#если альфа = 1% или 0.01, то подтверждается нулевая гипотеза, т.к. pvalue больше альфа